export enum Icons {
  BACK = require('./back.png'),
  BELL = require('./bell.png'),
  CARET_LEFT = require('./caretLeft.png'),
  CARET_RIGHT = require('./caretRight.png'),
  CHECK = require('./check.png'),
  CLAP = require('./demo/clap.png'),
  COMMUNITY = require('./demo/community.png'),
  COMPONENTS = require('./demo/components.png'),
  DEBUG = require('./demo/debug.png'),
  GITHUB = require('./demo/github.png'),
  HEART = require('./demo/heart.png'),
  HIDDEN = require('./hidden.png'),
  LADYBUG = require('./ladybug.png'),
  LOCK = require('./lock.png'),
  MENU = require('./menu.png'),
  MORE = require('./more.png'),
  PIN = require('./demo/pin.png'),
  PODCAST = require('./demo/podcast.png'),
  SETTINGS = require('./settings.png'),
  SLACK = require('./demo/slack.png'),
  VIEW = require('./view.png'),
  X = require('./x.png'),
}
